python run_summarization.py \
    --model_name_or_path t5-base \
    --do_train \
    --do_eval \
    --dataset_name allenai/mup \
    --source_prefix "summarize: " \
    --output_dir tmp/outputs/ \
    --per_device_train_batch_size=12 \
    --per_device_eval_batch_size=16 \
    --overwrite_output_dir \
    --predict_with_generate \
    --summary_column summary \
    --text_column text $@